### ISSUE TITLE
Documentation Suggestion

### ISSUE THREAD

**Issue by pgallastegui** [voiceittech/VoiceIt2-WebSDK#17]
On Readme.md, specify the nature of the 'content_language' initializing parameter. Is it just the ISO language (for example "en") or the ISO Language+Country Code ("en-US"), or the plain English language ("English")?

**Comment by gilgameshskytrooper** [comment]
This will be `en-US`

**Comment by hasismaeel5** [comment]
@pgallastegui please refer to https://api.voiceit.io/#content-languages-with-upcharge for content language codes
